"""fix history4

Revision ID: 0e5245f7df3d
Revises: ec9535585d5c
Create Date: 2026-05-03 14:17:25.917428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5245f7df3d'
down_revision: Union[str, Sequence[str], None] = 'ec9535585d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'history', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'history', 'anime_list', ['anime_id'], ['anime_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.drop_constraint(None, 'history', type_='foreignkey')
    # ### end Alembic commands ###
