"""jadvalga_yangi_ozgarishlar

Revision ID: 2dbfa094cd39
Revises: 564ae24e5aa3
Create Date: 2026-04-23 13:49:20.865649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dbfa094cd39'
down_revision: Union[str, Sequence[str], None] = '564ae24e5aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
