"""init

Revision ID: 40d67977d54c
Revises: f61ea53597e9
Create Date: 2026-05-02 00:09:13.587312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d67977d54c'
down_revision: Union[str, Sequence[str], None] = 'f61ea53597e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime_list', 'rating_sum',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_index(op.f('idx_history_user_anime'), table_name='history')
    op.drop_constraint(op.f('uix_user_anime'), 'history', type_='unique')
    op.create_unique_constraint('uix_user_anime_history', 'history', ['user_id', 'anime_id'])
    op.add_column('users', sa.Column('last_redirected_channel', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('referred_by_channel', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index('idx_points', 'users', ['points'], unique=False)
    op.create_index('idx_referral_count', 'users', ['referral_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_referral_count', table_name='users')
    op.drop_index('idx_points', table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_column('users', 'referred_by_channel')
    op.drop_column('users', 'last_redirected_channel')
    op.drop_constraint('uix_user_anime_history', 'history', type_='unique')
    op.create_unique_constraint(op.f('uix_user_anime'), 'history', ['user_id', 'anime_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_history_user_anime'), 'history', ['user_id', 'anime_id'], unique=False)
    op.alter_column('anime_list', 'rating_sum',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###
