"""fix_admin_role_enum

Revision ID: 45edf090bb86
Revises: a1e7bf3fbf32
Create Date: 2026-06-19 11:18:00.275853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45edf090bb86'
down_revision: Union[str, Sequence[str], None] = 'a1e7bf3fbf32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_settings_role'), table_name='admin_settings')
    op.alter_column('advertisements', 'ad_type',
               existing_type=postgresql.ENUM('banner', 'post', 'video', name='ad_type'),
               type_=sa.Enum('banner', 'post', 'video', name='constraint_ad_type'),
               existing_nullable=False)
    op.drop_index(op.f('ix_advertisements_ad_type'), table_name='advertisements')
    op.drop_index(op.f('ix_advertisements_is_active'), table_name='advertisements')
    op.drop_index(op.f('ix_advertisements_target_group'), table_name='advertisements')
    op.drop_index(op.f('ix_anime_list_title'), table_name='anime_list')
    op.drop_index(op.f('ix_anime_list_year'), table_name='anime_list')
    op.drop_index(op.f('ix_channels_is_active'), table_name='channels')
    op.drop_index(op.f('ix_comments_anime_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_fan_groups_is_active'), table_name='fan_groups')
    op.drop_index(op.f('ix_fan_groups_is_vip'), table_name='fan_groups')
    op.drop_index(op.f('ix_history_anime_id'), table_name='history')
    op.drop_index(op.f('ix_history_user_id'), table_name='history')
    op.alter_column('outbox_events', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('outbox_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('tickets', 'status',
               existing_type=postgresql.ENUM('open', 'closed', 'pending', name='ticket_status'),
               type_=sa.Enum('open', 'closed', 'pending', name='constraint_ticket_status'),
               existing_nullable=False)
    op.drop_index(op.f('ix_tickets_created_at'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_users_referral_count'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_referral_count'), 'users', ['referral_count'], unique=False)
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_created_at'), 'tickets', ['created_at'], unique=False)
    op.alter_column('tickets', 'status',
               existing_type=sa.Enum('open', 'closed', 'pending', name='constraint_ticket_status'),
               type_=postgresql.ENUM('open', 'closed', 'pending', name='ticket_status'),
               existing_nullable=False)
    op.alter_column('outbox_events', 'payload',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('outbox_events', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_index(op.f('ix_history_user_id'), 'history', ['user_id'], unique=False)
    op.create_index(op.f('ix_history_anime_id'), 'history', ['anime_id'], unique=False)
    op.create_index(op.f('ix_fan_groups_is_vip'), 'fan_groups', ['is_vip'], unique=False)
    op.create_index(op.f('ix_fan_groups_is_active'), 'fan_groups', ['is_active'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_comments_anime_id'), 'comments', ['anime_id'], unique=False)
    op.create_index(op.f('ix_channels_is_active'), 'channels', ['is_active'], unique=False)
    op.create_index(op.f('ix_anime_list_year'), 'anime_list', ['year'], unique=False)
    op.create_index(op.f('ix_anime_list_title'), 'anime_list', ['title'], unique=False)
    op.create_index(op.f('ix_advertisements_target_group'), 'advertisements', ['target_group'], unique=False)
    op.create_index(op.f('ix_advertisements_is_active'), 'advertisements', ['is_active'], unique=False)
    op.create_index(op.f('ix_advertisements_ad_type'), 'advertisements', ['ad_type'], unique=False)
    op.alter_column('advertisements', 'ad_type',
               existing_type=sa.Enum('banner', 'post', 'video', name='constraint_ad_type'),
               type_=postgresql.ENUM('banner', 'post', 'video', name='ad_type'),
               existing_nullable=False)
    op.create_index(op.f('ix_admin_settings_role'), 'admin_settings', ['role'], unique=False)
    # ### end Alembic commands ###
