"""add description and languag

Revision ID: 48889a1dbddb
Revises: b835f022993f
Create Date: 2026-05-30 20:26:58.596179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48889a1dbddb'
down_revision: Union[str, Sequence[str], None] = 'b835f022993f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('priority', sa.Integer(), nullable=False))
    op.alter_column('outbox_events', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_index(op.f('ix_outbox_events_priority'), 'outbox_events', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_events_priority'), table_name='outbox_events')
    op.alter_column('outbox_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('outbox_events', 'priority')
    # ### end Alembic commands ###
