"""initial_migration

Revision ID: 5ad713efa481
Revises: 
Create Date: 2026-05-04 22:14:58.535470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad713efa481'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ad_type', sa.Enum('banner', 'post', 'video', name='ad_type'), nullable=False),
    sa.Column('target_group', sa.String(length=50), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ad_active', 'advertisements', ['is_active'], unique=False)
    op.create_index('idx_ad_target', 'advertisements', ['target_group'], unique=False)
    op.create_index('idx_ad_type', 'advertisements', ['ad_type'], unique=False)
    op.create_index(op.f('ix_advertisements_ad_type'), 'advertisements', ['ad_type'], unique=False)
    op.create_index(op.f('ix_advertisements_created_at'), 'advertisements', ['created_at'], unique=False)
    op.create_index(op.f('ix_advertisements_end_date'), 'advertisements', ['end_date'], unique=False)
    op.create_index(op.f('ix_advertisements_is_active'), 'advertisements', ['is_active'], unique=False)
    op.create_index(op.f('ix_advertisements_target_group'), 'advertisements', ['target_group'], unique=False)
    op.create_table('anime_list',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('poster_id', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('rating_sum', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('views_week', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('anime_id')
    )
    op.create_index('idx_anime_search', 'anime_list', ['title'], unique=False)
    op.create_index('idx_anime_year', 'anime_list', ['year'], unique=False)
    op.create_index(op.f('ix_anime_list_title'), 'anime_list', ['title'], unique=False)
    op.create_index(op.f('ix_anime_list_views_week'), 'anime_list', ['views_week'], unique=False)
    op.create_index(op.f('ix_anime_list_year'), 'anime_list', ['year'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_channel_active', 'channels', ['is_active'], unique=False)
    op.create_index(op.f('ix_channels_channel_id'), 'channels', ['channel_id'], unique=True)
    op.create_index(op.f('ix_channels_is_active'), 'channels', ['is_active'], unique=False)
    op.create_table('fan_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('is_vip', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fan_active', 'fan_groups', ['is_active'], unique=False)
    op.create_index('idx_fan_vip', 'fan_groups', ['is_vip'], unique=False)
    op.create_index(op.f('ix_fan_groups_is_active'), 'fan_groups', ['is_active'], unique=False)
    op.create_index(op.f('ix_fan_groups_is_vip'), 'fan_groups', ['is_vip'], unique=False)
    op.create_index(op.f('ix_fan_groups_name'), 'fan_groups', ['name'], unique=True)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_table('help_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_help_pages_page_number'), 'help_pages', ['page_number'], unique=True)
    op.create_table('outbox_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('aggregate', sa.String(), nullable=False),
    sa.Column('aggregate_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_aggregate'), 'outbox_events', ['aggregate'], unique=False)
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_created_at'), 'outbox_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_processed'), 'outbox_events', ['processed'], unique=False)
    op.create_index(op.f('ix_outbox_events_processed_at'), 'outbox_events', ['processed_at'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('user', 'vip', 'admin', name='user_status'), nullable=False),
    sa.Column('vip_expire_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_mode', sa.Boolean(), nullable=False),
    sa.Column('referral_count', sa.Integer(), nullable=False),
    sa.Column('last_redirected_channel', sa.String(length=50), nullable=True),
    sa.Column('referred_by_channel', sa.String(length=50), nullable=True),
    sa.Column('referred_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['referred_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('idx_user_points_fast', 'users', ['status', 'points'], unique=False)
    op.create_index('idx_user_ref_fast', 'users', ['referral_count'], unique=False)
    op.create_index(op.f('ix_users_joined_at'), 'users', ['joined_at'], unique=False)
    op.create_index(op.f('ix_users_points'), 'users', ['points'], unique=False)
    op.create_index(op.f('ix_users_referral_count'), 'users', ['referral_count'], unique=False)
    op.create_index(op.f('ix_users_referred_by'), 'users', ['referred_by'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('admin_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'moderator', name='admin_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_admin_role', 'admin_settings', ['role'], unique=False)
    op.create_index(op.f('ix_admin_settings_role'), 'admin_settings', ['role'], unique=False)
    op.create_index(op.f('ix_admin_settings_user_id'), 'admin_settings', ['user_id'], unique=True)
    op.create_table('anime_episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime_list.anime_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id', 'episode')
    )
    op.create_index(op.f('ix_anime_episodes_anime_id'), 'anime_episodes', ['anime_id'], unique=False)
    op.create_index(op.f('ix_anime_episodes_file_id'), 'anime_episodes', ['file_id'], unique=False)
    op.create_table('anime_genres',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime_list.anime_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('anime_id', 'genre_id')
    )
    op.create_index('idx_anime_id', 'anime_genres', ['anime_id'], unique=False)
    op.create_index('idx_genre_id', 'anime_genres', ['genre_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime_list.anime_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comment_anime', 'comments', ['anime_id'], unique=False)
    op.create_index('idx_comment_parent', 'comments', ['parent_id'], unique=False)
    op.create_index('idx_comment_user', 'comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_comments_anime_id'), 'comments', ['anime_id'], unique=False)
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime_list.anime_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'anime_id')
    )
    op.create_index('idx_fav_anime', 'favorites', ['anime_id'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime_list.anime_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_history_anime', 'history', ['anime_id'], unique=False)
    op.create_index('idx_history_user', 'history', ['user_id'], unique=False)
    op.create_index(op.f('ix_history_anime_id'), 'history', ['anime_id'], unique=False)
    op.create_index(op.f('ix_history_user_id'), 'history', ['user_id'], unique=False)
    op.create_index(op.f('ix_history_watched_at'), 'history', ['watched_at'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', 'pending', name='ticket_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ticket_created', 'tickets', ['created_at'], unique=False)
    op.create_index('idx_ticket_status', 'tickets', ['status'], unique=False)
    op.create_index('idx_ticket_user', 'tickets', ['user_id'], unique=False)
    op.create_index(op.f('ix_tickets_created_at'), 'tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_tickets_file_id'), 'tickets', ['file_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_user_id'), 'tickets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_user_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_file_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_created_at'), table_name='tickets')
    op.drop_index('idx_ticket_user', table_name='tickets')
    op.drop_index('idx_ticket_status', table_name='tickets')
    op.drop_index('idx_ticket_created', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_history_watched_at'), table_name='history')
    op.drop_index(op.f('ix_history_user_id'), table_name='history')
    op.drop_index(op.f('ix_history_anime_id'), table_name='history')
    op.drop_index('idx_history_user', table_name='history')
    op.drop_index('idx_history_anime', table_name='history')
    op.drop_table('history')
    op.drop_index('idx_fav_anime', table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_anime_id'), table_name='comments')
    op.drop_index('idx_comment_user', table_name='comments')
    op.drop_index('idx_comment_parent', table_name='comments')
    op.drop_index('idx_comment_anime', table_name='comments')
    op.drop_table('comments')
    op.drop_index('idx_genre_id', table_name='anime_genres')
    op.drop_index('idx_anime_id', table_name='anime_genres')
    op.drop_table('anime_genres')
    op.drop_index(op.f('ix_anime_episodes_file_id'), table_name='anime_episodes')
    op.drop_index(op.f('ix_anime_episodes_anime_id'), table_name='anime_episodes')
    op.drop_table('anime_episodes')
    op.drop_index(op.f('ix_admin_settings_user_id'), table_name='admin_settings')
    op.drop_index(op.f('ix_admin_settings_role'), table_name='admin_settings')
    op.drop_index('idx_admin_role', table_name='admin_settings')
    op.drop_table('admin_settings')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_referred_by'), table_name='users')
    op.drop_index(op.f('ix_users_referral_count'), table_name='users')
    op.drop_index(op.f('ix_users_points'), table_name='users')
    op.drop_index(op.f('ix_users_joined_at'), table_name='users')
    op.drop_index('idx_user_ref_fast', table_name='users')
    op.drop_index('idx_user_points_fast', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_outbox_events_processed_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_processed'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_created_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_help_pages_page_number'), table_name='help_pages')
    op.drop_table('help_pages')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_fan_groups_name'), table_name='fan_groups')
    op.drop_index(op.f('ix_fan_groups_is_vip'), table_name='fan_groups')
    op.drop_index(op.f('ix_fan_groups_is_active'), table_name='fan_groups')
    op.drop_index('idx_fan_vip', table_name='fan_groups')
    op.drop_index('idx_fan_active', table_name='fan_groups')
    op.drop_table('fan_groups')
    op.drop_index(op.f('ix_channels_is_active'), table_name='channels')
    op.drop_index(op.f('ix_channels_channel_id'), table_name='channels')
    op.drop_index('idx_channel_active', table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_anime_list_year'), table_name='anime_list')
    op.drop_index(op.f('ix_anime_list_views_week'), table_name='anime_list')
    op.drop_index(op.f('ix_anime_list_title'), table_name='anime_list')
    op.drop_index('idx_anime_year', table_name='anime_list')
    op.drop_index('idx_anime_search', table_name='anime_list')
    op.drop_table('anime_list')
    op.drop_index(op.f('ix_advertisements_target_group'), table_name='advertisements')
    op.drop_index(op.f('ix_advertisements_is_active'), table_name='advertisements')
    op.drop_index(op.f('ix_advertisements_end_date'), table_name='advertisements')
    op.drop_index(op.f('ix_advertisements_created_at'), table_name='advertisements')
    op.drop_index(op.f('ix_advertisements_ad_type'), table_name='advertisements')
    op.drop_index('idx_ad_type', table_name='advertisements')
    op.drop_index('idx_ad_target', table_name='advertisements')
    op.drop_index('idx_ad_active', table_name='advertisements')
    op.drop_table('advertisements')
    # ### end Alembic commands ###
