"""fix timezone4

Revision ID: 9da5a3ff100d
Revises: 92f84e4bdb59
Create Date: 2026-05-03 13:37:23.076383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da5a3ff100d'
down_revision: Union[str, Sequence[str], None] = '92f84e4bdb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_episode_anime'), table_name='anime_episodes')
    op.create_index('idx_episode_fast', 'anime_episodes', ['anime_id', 'episode'], unique=False)
    op.create_index(op.f('ix_anime_episodes_anime_id'), 'anime_episodes', ['anime_id'], unique=False)
    op.create_index(op.f('ix_anime_episodes_episode'), 'anime_episodes', ['episode'], unique=False)
    op.create_index('idx_anime_genre_fast', 'anime_genre', ['anime_id', 'genre_id'], unique=False)
    op.drop_constraint(op.f('anime_list_title_key'), 'anime_list', type_='unique')
    op.drop_index(op.f('idx_anime_title'), table_name='anime_list')
    op.drop_index(op.f('idx_anime_year'), table_name='anime_list')
    op.create_index('idx_anime_fast_search', 'anime_list', ['title', 'year'], unique=False)
    op.create_index(op.f('ix_anime_list_title'), 'anime_list', ['title'], unique=True)
    op.create_index(op.f('ix_anime_list_views_week'), 'anime_list', ['views_week'], unique=False)
    op.create_index(op.f('ix_anime_list_year'), 'anime_list', ['year'], unique=False)
    op.drop_column('anime_list', 'fandub')
    op.drop_column('anime_list', 'description')
    op.drop_column('anime_list', 'lang')
    op.alter_column('comments', 'anime_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index(op.f('idx_comment_anime'), table_name='comments')
    op.create_index(op.f('ix_comments_anime_id'), 'comments', ['anime_id'], unique=False)
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.drop_constraint(op.f('comments_anime_id_fkey'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('comments_user_id_fkey'), 'comments', type_='foreignkey')
    op.alter_column('favorites', 'anime_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('history', 'anime_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_constraint(op.f('uix_user_anime_history'), 'history', type_='unique')
    op.create_index(op.f('ix_history_anime_id'), 'history', ['anime_id'], unique=False)
    op.create_index(op.f('ix_history_user_id'), 'history', ['user_id'], unique=False)
    op.create_index(op.f('ix_history_watched_at'), 'history', ['watched_at'], unique=False)
    op.drop_constraint(op.f('history_user_id_fkey'), 'history', type_='foreignkey')
    op.drop_constraint(op.f('history_anime_id_fkey'), 'history', type_='foreignkey')
    op.drop_column('history', 'last_episode')
    op.create_index(op.f('ix_outbox_events_aggregate'), 'outbox_events', ['aggregate'], unique=False)
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_created_at'), 'outbox_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.drop_index(op.f('idx_points'), table_name='users')
    op.drop_index(op.f('idx_referral_count'), table_name='users')
    op.create_index('idx_user_points_fast', 'users', ['points', 'status'], unique=False)
    op.create_index('idx_user_ref_fast', 'users', ['referral_count'], unique=False)
    op.create_index(op.f('ix_users_points'), 'users', ['points'], unique=False)
    op.create_index(op.f('ix_users_referral_count'), 'users', ['referral_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_referral_count'), table_name='users')
    op.drop_index(op.f('ix_users_points'), table_name='users')
    op.drop_index('idx_user_ref_fast', table_name='users')
    op.drop_index('idx_user_points_fast', table_name='users')
    op.create_index(op.f('idx_referral_count'), 'users', ['referral_count'], unique=False)
    op.create_index(op.f('idx_points'), 'users', ['points'], unique=False)
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_created_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate'), table_name='outbox_events')
    op.add_column('history', sa.Column('last_episode', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('history_anime_id_fkey'), 'history', 'anime_list', ['anime_id'], ['anime_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('history_user_id_fkey'), 'history', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_history_watched_at'), table_name='history')
    op.drop_index(op.f('ix_history_user_id'), table_name='history')
    op.drop_index(op.f('ix_history_anime_id'), table_name='history')
    op.create_unique_constraint(op.f('uix_user_anime_history'), 'history', ['user_id', 'anime_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('history', 'anime_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('favorites', 'anime_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_foreign_key(op.f('comments_user_id_fkey'), 'comments', 'users', ['user_id'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('comments_anime_id_fkey'), 'comments', 'anime_list', ['anime_id'], ['anime_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_anime_id'), table_name='comments')
    op.create_index(op.f('idx_comment_anime'), 'comments', ['anime_id'], unique=False)
    op.alter_column('comments', 'anime_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('anime_list', sa.Column('lang', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('anime_list', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('anime_list', sa.Column('fandub', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_anime_list_year'), table_name='anime_list')
    op.drop_index(op.f('ix_anime_list_views_week'), table_name='anime_list')
    op.drop_index(op.f('ix_anime_list_title'), table_name='anime_list')
    op.drop_index('idx_anime_fast_search', table_name='anime_list')
    op.create_index(op.f('idx_anime_year'), 'anime_list', ['year'], unique=False)
    op.create_index(op.f('idx_anime_title'), 'anime_list', ['title'], unique=False)
    op.create_unique_constraint(op.f('anime_list_title_key'), 'anime_list', ['title'], postgresql_nulls_not_distinct=False)
    op.drop_index('idx_anime_genre_fast', table_name='anime_genre')
    op.drop_index(op.f('ix_anime_episodes_episode'), table_name='anime_episodes')
    op.drop_index(op.f('ix_anime_episodes_anime_id'), table_name='anime_episodes')
    op.drop_index('idx_episode_fast', table_name='anime_episodes')
    op.create_index(op.f('idx_episode_anime'), 'anime_episodes', ['anime_id'], unique=False)
    # ### end Alembic commands ###
