"""add description and languagee

Revision ID: aa52870e36b1
Revises: 48889a1dbddb
Create Date: 2026-06-03 18:12:04.555845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa52870e36b1'
down_revision: Union[str, Sequence[str], None] = '48889a1dbddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('event_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_outbox_events_event_hash'), 'outbox_events', ['event_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_events_event_hash'), table_name='outbox_events')
    op.drop_column('outbox_events', 'event_hash')
    # ### end Alembic commands ###
