"""Add description and languages columns to anime_list table

Revision ID: b835f022993f
Revises: da2caf756e7e
Create Date: 2026-05-26 22:38:57.963972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b835f022993f'
down_revision: Union[str, Sequence[str], None] = 'da2caf756e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime_list', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('anime_list', sa.Column('languages', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime_list', 'languages')
    op.drop_column('anime_list', 'description')
    # ### end Alembic commands ###
