"""fix timezone2

Revision ID: e2c42ded5ec7
Revises: f1e8a5c63fb7
Create Date: 2026-05-02 20:42:37.880822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c42ded5ec7'
down_revision: Union[str, Sequence[str], None] = 'f1e8a5c63fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('event_type', sa.String(), nullable=False))
    op.add_column('outbox_events', sa.Column('payload', sa.Text(), nullable=False))
    op.add_column('outbox_events', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('outbox_events', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_outbox_events_processed'), 'outbox_events', ['processed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_events_processed'), table_name='outbox_events')
    op.drop_column('outbox_events', 'processed_at')
    op.drop_column('outbox_events', 'retry_count')
    op.drop_column('outbox_events', 'payload')
    op.drop_column('outbox_events', 'event_type')
    # ### end Alembic commands ###
