"""fix error key 

Revision ID: e654361636d5
Revises: 0e5245f7df3d
Create Date: 2026-05-03 14:34:27.189561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e654361636d5'
down_revision: Union[str, Sequence[str], None] = '0e5245f7df3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'comments', 'anime_list', ['anime_id'], ['anime_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    # ### end Alembic commands ###
