"""init

Revision ID: eea858cc4c20
Revises: c731ade07c22
Create Date: 2026-05-02 15:14:23.562194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eea858cc4c20'
down_revision: Union[str, Sequence[str], None] = 'c731ade07c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('channels', 'url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('channels_channel_id_key'), 'channels', type_='unique')
    op.create_index(op.f('ix_channels_channel_id'), 'channels', ['channel_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channels_channel_id'), table_name='channels')
    op.create_unique_constraint(op.f('channels_channel_id_key'), 'channels', ['channel_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('channels', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('channels', 'url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('channels', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
