"""Initial migration

Revision ID: f61ea53597e9
Revises: 1478c06f906e
Create Date: 2026-04-28 19:07:02.590265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61ea53597e9'
down_revision: Union[str, Sequence[str], None] = '1478c06f906e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('aggregate', sa.String(), nullable=False),
    sa.Column('aggregate_id', sa.String(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_processed'), 'outbox_events', ['processed'], unique=False)
    op.alter_column('anime_list', 'rating_sum',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_index(op.f('idx_history_user_anime'), table_name='history')
    op.drop_constraint(op.f('uix_user_anime'), 'history', type_='unique')
    op.create_unique_constraint('uix_user_anime_history', 'history', ['user_id', 'anime_id'])
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_constraint('uix_user_anime_history', 'history', type_='unique')
    op.create_unique_constraint(op.f('uix_user_anime'), 'history', ['user_id', 'anime_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_history_user_anime'), 'history', ['user_id', 'anime_id'], unique=False)
    op.alter_column('anime_list', 'rating_sum',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_index(op.f('ix_outbox_events_processed'), table_name='outbox_events')
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
